--
--STAR SCHEMA
--




DROP TABLE DATA_WAREHOUSE.COMPANY;
DROP TABLE DATA_WAREHOUSE.REVENUE;
DROP TABLE DATA_WAREHOUSE.ONLINE_PRODUCT_TYPE;
DROP TABLE DATA_WAREHOUSE.OPT_PURCHASE_RATE;
DROP TABLE DATA_WAREHOUSE.INDUSTRY;
DROP TABLE DATA_WAREHOUSE.BUSINESS_INDICATORS;

--INSERT INTO DATA_WAREHOUSE.COMPANY VALUES ('Amazon');
--INSERT INTO DATA_WAREHOUSE.REVENUE VALUES ('Amazon', 2010, 300);
--INSERT INTO DATA_WAREHOUSE.ONLINE_PRODUCT_TYPE VALUES ('Phone');
--INSERT INTO DATA_WAREHOUSE.OPT_PURCHASE_RATE VALUES ('Phone', 2010, 73.7);
--INSERT INTO DATA_WAREHOUSE.INDUSTRY VALUES ('Electronics');
--INSERT INTO DATA_WAREHOUSE.BUSINESS_INDICATORS VALUES ('Electronics', 2010, 300, 9.8, 300000, 25000, 50);



-- 'I' = INT over DATE because less disk space required; faster performance (only stores year)

CREATE TABLE DATA_WAREHOUSE.COMPANY (
COMPANY VARCHAR(255) PRIMARY KEY
);

CREATE TABLE DATA_WAREHOUSE.REVENUE (
COMPANY VARCHAR(255) REFERENCES DATA_WAREHOUSE.COMPANY(COMPANY),
REVENUE_YEAR INT, --I
REVENUE_IN_MILLION_EUR DECIMAL(10,2), 
PRIMARY KEY(COMPANY, REVENUE_YEAR)
);




CREATE TABLE DATA_WAREHOUSE.ONLINE_PRODUCT_TYPE (
ONLINE_PRODUCT_TYPE VARCHAR(255) PRIMARY KEY
);

CREATE TABLE DATA_WAREHOUSE.OPT_PURCHASE_RATE (
PURCHASE_YEAR_Q1 INT, --I --data was only recorded during first quarter of the year
ONLINE_PRODUCT_TYPE VARCHAR(255) REFERENCES DATA_WAREHOUSE.ONLINE_PRODUCT_TYPE(ONLINE_PRODUCT_TYPE),
PURCHASE_RATE DECIMAL(10, 1),
PRIMARY KEY(ONLINE_PRODUCT_TYPE, PURCHASE_YEAR_Q1)
);




CREATE TABLE DATA_WAREHOUSE.INDUSTRY (
INDUSTRY VARCHAR(255) PRIMARY KEY
);

CREATE TABLE DATA_WAREHOUSE.BUSINESS_INDICATORS (
STATISTICAL_YEAR INT, --I
INDUSTRY VARCHAR(255) REFERENCES DATA_WAREHOUSE.INDUSTRY(INDUSTRY),
TOTAL_REVENUE_IN_MILLION_EUR INT,
REVENUE_SHARE_ECOMMERCE DECIMAL(3, 1),
TOTAL_EMPLOYEES INT,
TOTAL_COMPANIES INT,
SUBSIDIES_BY_GERMANY_IN_MILLION_EUR INT,
PRIMARY KEY(INDUSTRY, STATISTICAL_YEAR)
);




--
--STAGING AREA
--


DROP TABLE DATA_WAREHOUSE.STAGING_ONLINESHOPPING;

-- 'D' = csv file uses comma as a decimal separator or fullstop to space out numbers, requiring to temporarily store the value as string

CREATE TABLE DATA_WAREHOUSE.STAGING_ONLINESHOPPING (
PURCHASE_YEAR_Q1 INT,
ONLINE_PRODUCT_TYPE VARCHAR(255),
PURCHASE_RATE VARCHAR(255), --D
PRIMARY KEY(PURCHASE_YEAR_Q1, ONLINE_PRODUCT_TYPE) 
);




CREATE TABLE DATA_WAREHOUSE.STAGING_REVENUE_EDEKA (
REVENUE_YEAR INT PRIMARY KEY,
REVENUE_IN_BILLION_EUR VARCHAR(255) --D
);

CREATE TABLE DATA_WAREHOUSE.STAGING_REVENUE_OTTO (
REVENUE_YEAR VARCHAR(255) PRIMARY KEY,
REVENUE_IN_MILLION_EUR VARCHAR(255) --D
);

CREATE TABLE DATA_WAREHOUSE.STAGING_REVENUE_CA (
REVENUE_YEAR VARCHAR(255) PRIMARY KEY,
REVENUE_IN_MILLION_EUR VARCHAR(255) --D
);

CREATE TABLE DATA_WAREHOUSE.STAGING_REVENUE_ZALANDO (
REVENUE_YEAR INT PRIMARY KEY,
REVENUE_IN_MILLION_EUR VARCHAR(255) --D
);

CREATE TABLE DATA_WAREHOUSE.STAGING_REVENUE_GALERIAKAUFHOF_AND_KARSTADT (
REVENUE_YEAR INT PRIMARY KEY,
REVENUE_GALERIAKAUFHOF_IN_BILLION_EUR VARCHAR(255), --D
REVENUE_KARSTADT_IN_BILLION_EUR VARCHAR(255) --D
);

CREATE TABLE DATA_WAREHOUSE.STAGING_REVENUE_AMAZON_GERMANY (
REVENUE_YEAR INT PRIMARY KEY,
REVENUE_IN_BILLION_USD VARCHAR(255) --D
);

CREATE TABLE DATA_WAREHOUSE.STAGING_REVENUE_NORMA (
REVENUE_YEAR INT PRIMARY KEY,
REVENUE_IN_MILLION_EUR VARCHAR(255) --D
);




CREATE TABLE DATA_WAREHOUSE.STAGING_BUSINESS_INDICATORS (
STATISTICAL_YEAR INT, 
INDUSTRY VARCHAR(255),
TOTAL_REVENUE_IN_MILLION_EUR INT,
REVENUE_SHARE_ECOMMERCE VARCHAR(255), --D
TOTAL_EMPLOYEES INT,
TOTAL_COMPANIES INT,
SUBSIDIES_BY_GERMANY_IN_MILLION_EUR INT,
PRIMARY KEY(INDUSTRY, STATISTICAL_YEAR)
);




--
--IMPORT TO STAGING AREA
--


--Full file paths are omitted 

IMPORT INTO DATA_WAREHOUSE.STAGING_ONLINESHOPPING (PURCHASE_YEAR_Q1, ONLINE_PRODUCT_TYPE, PURCHASE_RATE)
FROM LOCAL CSV FILE 'C:\...\DW Projekt\onlinehandel_daten.csv'
(1,3, 7)
ENCODING = 'WINDOWS-1252'
NULL = '-'
ROW SEPARATOR = 'CRLF'
COLUMN SEPARATOR = ';'
SKIP = 10;




IMPORT INTO DATA_WAREHOUSE.STAGING_REVENUE_EDEKA (REVENUE_YEAR, REVENUE_IN_BILLION_EUR)
FROM LOCAL CSV FILE 'C:\...\DW Projekt\statistic_id72803_umsatz-der-edeka-gruppe-in-deutschland-bis-2022.csv'
ROW SEPARATOR = 'CRLF'
COLUMN SEPARATOR = ';'
SKIP = 3;

IMPORT INTO DATA_WAREHOUSE.STAGING_REVENUE_OTTO (REVENUE_YEAR, REVENUE_IN_MILLION_EUR)
FROM LOCAL CSV FILE 'C:\...\DW Projekt\statistic_id160251_umsatz-von-otto-bis-2022-23.csv'
ROW SEPARATOR = 'CRLF'
COLUMN SEPARATOR = ';'
SKIP = 3;

IMPORT INTO DATA_WAREHOUSE.STAGING_REVENUE_CA (REVENUE_YEAR, REVENUE_IN_MILLION_EUR)
FROM LOCAL CSV FILE 'C:\...\DW Projekt\statistic_id223665_umsatz-von-c-a-in-deutschland-bis-2022.csv'
ROW SEPARATOR = 'CRLF'
COLUMN SEPARATOR = ';'
SKIP = 3;

IMPORT INTO DATA_WAREHOUSE.STAGING_REVENUE_ZALANDO (REVENUE_YEAR, REVENUE_IN_MILLION_EUR)
FROM LOCAL CSV FILE 'C:\...\DW Projekt\statistic_id247692_umsatz-von-zalando-bis-2022.csv'
ROW SEPARATOR = 'CRLF'
COLUMN SEPARATOR = ';'
SKIP = 3;

IMPORT INTO DATA_WAREHOUSE.STAGING_REVENUE_AMAZON_GERMANY (REVENUE_YEAR, REVENUE_IN_BILLION_USD)
FROM LOCAL CSV FILE 'C:\...\DW Projekt\statistic_id374731_umsatz-von-amazon-in-deutschland-und-weltweit-bis-2022.csv'
(1,2)
ROW SEPARATOR = 'CRLF'
COLUMN SEPARATOR = ';'
SKIP = 3;

IMPORT INTO DATA_WAREHOUSE.STAGING_REVENUE_NORMA (REVENUE_YEAR, REVENUE_IN_MILLION_EUR)
FROM LOCAL CSV FILE 'C:\...\DW Projekt\statistic_id516905_umsatz-von-norma-in-deutschland-bis-2022.csv'
ROW SEPARATOR = 'CRLF'
COLUMN SEPARATOR = ';'
SKIP = 3;




IMPORT INTO DATA_WAREHOUSE.STAGING_BUSINESS_INDICATORS (STATISTICAL_YEAR, INDUSTRY, TOTAL_COMPANIES, TOTAL_EMPLOYEES, TOTAL_REVENUE_IN_MILLION_EUR, REVENUE_SHARE_ECOMMERCE, SUBSIDIES_BY_GERMANY_IN_MILLION_EUR)
FROM LOCAL CSV FILE 'C:\...\Data Warehouse\DW Projekt\einzelhandel_zahlen.csv'
(1, 3, 4, 5, 6, 8, 9)
ENCODING = 'WINDOWS-1252'
NULL = '-'
ROW SEPARATOR = 'LF'
COLUMN SEPARATOR = ';'
SKIP = 8;